-- Baseline schema (sinh từ Hibernate, khớp entity 100%).
-- DB Supabase hiện tại đã có sẵn schema này -> Flyway baseline-on-migrate sẽ ĐÁNH DẤU
-- V1 là baseline (KHÔNG chạy lại). File này chỉ THỰC SỰ chạy trên DB MỚI (rỗng).

create table achivements (active boolean not null, sort_order integer not null, target integer, target2 integer, created_at timestamp(6) with time zone not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone not null, category varchar(16) not null check ((category in ('PER_HABIT','ACCOUNT'))), type varchar(32) not null check ((type in ('STREAK','TOTAL_CHECKINS','MULTI_STREAK','HABIT_COUNT','PERFECT_WEEK','HOLIDAY_CHECKIN'))), code varchar(64) not null unique, name varchar(128) not null, description varchar(255), icon varchar(255), primary key (id));
create table checkins (checkin_date date not null, created_at timestamp(6) with time zone not null, habit_id bigint not null, id bigint generated by default as identity, note varchar(255), primary key (id), constraint uq_checkin_habit_date unique (habit_id, checkin_date));
create table habits (best_streak integer not null, current_streak integer not null, is_paused boolean not null, last_checkin_date date, remind_time time(0), created_at timestamp(6) with time zone not null, icon_id bigint unique, id bigint generated by default as identity, updated_at timestamp(6) with time zone not null, user_id bigint, frequency varchar(255), name varchar(255), note varchar(255), primary key (id));
create table icons (is_actived boolean not null, created_at timestamp(6) with time zone not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone not null, icon varchar(255), icon_color varchar(255), icon_ref varchar(255), primary key (id));
create table oauth_accounts (created_at timestamp(6) with time zone not null, id bigint generated by default as identity, user_id bigint not null, provider varchar(16) not null check ((provider in ('GOOGLE'))), email varchar(255), provider_user_id varchar(255) not null, primary key (id), constraint uq_oauth_provider_user unique (provider, provider_user_id));
create table refresh_tokens (revoked boolean not null, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, user_id bigint not null, token_hash varchar(255) not null unique, primary key (id));
create table user_achivements (shared boolean not null, definition_id bigint not null, habit_id bigint, id bigint generated by default as identity, unlocked_at timestamp(6) with time zone not null, user_id bigint not null, primary key (id), constraint uq_user_ach_habit unique (user_id, definition_id, habit_id));
create table users (role smallint check ((role between 0 and 1)), created_at timestamp(6) with time zone not null, id bigint generated by default as identity, updated_at timestamp(6) with time zone not null, email varchar(255), password varchar(255), username varchar(255), primary key (id));
alter table if exists checkins add constraint FKccsnc541yawn636shrdwmkpyb foreign key (habit_id) references habits;
alter table if exists habits add constraint FK6jootdn2wvqk4rnlfr5ryyrvn foreign key (icon_id) references icons;
alter table if exists habits add constraint FKg3n2qqwmsyv3517xdcosouk9i foreign key (user_id) references users;
alter table if exists oauth_accounts add constraint FKn6j2b3ur1fcj3vkodrmqtdxmi foreign key (user_id) references users;
alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;
alter table if exists user_achivements add constraint FK4dg54ajcd66feomxuq9gwkwh foreign key (definition_id) references achivements;
alter table if exists user_achivements add constraint FKs14ykliakfg9rg90bbrn4qw7m foreign key (habit_id) references habits;
alter table if exists user_achivements add constraint FKtjegpe2x8gibd0uofbqy1b028 foreign key (user_id) references users;
