-- Lưu Web Push subscription của từng thiết bị/trình duyệt của user.
-- endpoint là URL push service (unique) + 2 khoá p256dh/auth để mã hoá payload.
create table push_subscriptions (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users,
    endpoint    varchar(512) not null unique,
    p256dh      varchar(255) not null,
    auth        varchar(255) not null,
    created_at  timestamp(6) with time zone not null
);
create index idx_push_sub_user on push_subscriptions (user_id);
