-- Token đặt lại mật khẩu: CHỈ lưu SHA-256 hash (giống refresh_tokens), token gốc chỉ nằm
-- trong link gửi qua email. Dùng 1 lần (used) và có hạn ngắn (expires_at).
create table password_reset_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(255) not null unique,
    expires_at timestamp(6) with time zone not null,
    used boolean not null default false,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_prt_user foreign key (user_id) references users
);
create index idx_prt_user on password_reset_tokens (user_id);
