-- Xác thực email khi đăng ký.
-- Cột email_verified: user ĐANG CÓ coi như đã xác thực (tránh khoá người dùng cũ);
-- user mới mặc định false (Hibernate insert tường minh false).
alter table users add column email_verified boolean not null default false;
update users set email_verified = true;
alter table users alter column email_verified set default false;

-- Token xác thực email: giống password_reset_tokens (chỉ lưu HASH, 1 lần, có hạn).
create table email_verification_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(255) not null unique,
    expires_at timestamp(6) with time zone not null,
    used boolean not null default false,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_evt_user foreign key (user_id) references users
);
create index idx_evt_user on email_verification_tokens (user_id);
