-- Đồng bộ 1 chiều habit -> Google Calendar.
-- Lưu event id Google trên từng habit để còn cập nhật/xoá event tương ứng.
alter table habits add column google_calendar_event_id varchar(255);

-- Kết nối Calendar của user: lưu Google refresh token (offline access) để lấy access token
-- mới khi cần gọi API. LƯU Ý BẢO MẬT: refresh token phải dùng lại được nên không hash được;
-- ở production nên mã hoá at-rest bằng khoá từ env. Mỗi user tối đa 1 kết nối (unique).
create table google_calendar_connections (
    id bigint generated by default as identity,
    user_id bigint not null unique,
    refresh_token varchar(512) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_gcc_user foreign key (user_id) references users
);
